export default function TemplatePreview({ pages }: { pages: string[] }) {
  return (
    <div className="grid grid-cols-[repeat(auto-fill,minmax(260px,1fr))] gap-5">
      {pages.map((svg, i) => (
        <figure key={i} className="flex flex-col gap-2">
          {/* Pages stay white in dark mode: they preview the paper you'll print on.
              The SVG is generated by our own backend; all text in it is escaped. */}
          <div
            className="overflow-hidden rounded-sm bg-white shadow-md ring-1 ring-foreground/10 [&_svg]:block [&_svg]:h-auto [&_svg]:w-full"
            dangerouslySetInnerHTML={{ __html: svg }}
          />
          <figcaption className="text-center text-xs text-muted-foreground">Page {i + 1}</figcaption>
        </figure>
      ))}
    </div>
  );
}
